sudo: false
language: node_js
node_js: 14
install: echo "Installation happens in the setup script"
cache: npm
notifications:
  email: false
branches:
  only:
    - main
script: npm run setup
after_script: npx codecov@3
